export default {
  login: '登录',
  recommended: '今日推荐',
  userinfo: '用户详情',
  userredact: '编辑资料',
  userlist: '用户列表',
  userlog: '登录日志',
  merchantslist:'商户列表',
  merchantsadd: '新增商户',
  merchantsupdate:'商户编辑',
  merchantsinfo:'商户详情',
  group: '团购',
  addGroup:'添加团购活动',
  updateGroup: '修改团购活动',
  scareBuying: '限时抢购',
  addScareGroup: '添加限时抢购活动',
  chatList: '购物客服列表',
  chatService: '购物客服',
  chatListGoods: '商品客服列表',
  chatServiceGoods: '商品客服',
  goodsclassify: '商品分类管理',
  goodsadd: '新增商品分类',
  goodsonsale: '在售商品管理',
  goodsupdate: '发布商品管理',
  goodssoldout: '下架商品管理',
  evaluatelist: '商品评价',
  evadetail: '商品评价详情',
  answerlist: '商品问答',
  answerdetail: '商品问答详情',
  goodswarehousing: '商品入库',
  goodsoutbound: '商品出库',
  orderlist: '订单列表',
  orderstate0: '订单详情',
  orderstate00: '订单详情',
  orderstate1: '订单详情',
  orderstate3: '订单详情',
  orderstate4: '订单详情',
  orderstate5: '订单详情',
  orderstate6: '订单详情',
  orderstate7: '订单详情',
  orderset: '订单设置',
  returnmoney: '退款申请单',
  returncargo: '退货申请单',
  tradecargo: '换货申请单',
  receipt: '收款单',
  refundorder: '退款单',
  dispatchbill: '发货单',
  Returned: '退货单',
  ordercarriage: '运费模板',
  ordercaradd: '新增运费模板',
  ordercarupdate: '修改运费模板',
  ordercarall: '合作物流',
  userquery: '用户账号查询',
  useradd: '添加新用户',
  userupdate: '修改用户信息',
  poweruserlog:'登录日志',
  departmentquery: '部门查询',
  departmentadd: '添加新部门',
  departmentupdate: '修改部门',
  rolequery: '角色查询',
  roleadd: '添加新角色',
  roleupdate: '修改角色',
  powerquery: '权限查询',
  poweradd: '添加新权限',
  powerupdate: '修改权限',
  statisticalTable: '统计表',
  accountList: '对账列表',
  AccountStatementHavebeencorrected: '对账详情',
  WeChatStatement: '微信对账单',
  wechatReconciliationDetails: '微信对账详情',
  disSet: '分销设置',
  distManagement: '分销商管理',
  distributionDetails: '分销商详情',
  statisticsData:'数据统计',
  employee:'用户考核',
  EmployeeInfo:'人员详情',
  EmployeeRedact:'考核编辑',
  activeList:'活动列表',
  redactActive:'活动编辑',
  audit:'商品审核',
  goodsDetails:'商品详情',
  feedback:'建议反馈',
  accountDetailsNotOutofAccount:'对账详情',
  fullreduction:'满减优惠',
  promotion:'限时优惠',
  merchant:'商户聊天',
  merchantDetails:'商户客服',
  processing:'建议反馈',
  sale_list:'售后列表',
  afterSale1:'订单取消',
  afterSale2:'订单取消',
  afterSale3:'订单取消',
  drawback1:'售后退款',
  drawback2:'售后退款',
  drawback3:'售后退款',
  supplierlist:'供应商列表',
  supplieradd: '新增供应商',
  supplierinfo: '供应商详情',
  supplierupdate: '修改供应商',
  withdrawal:'分销提现',
  myCoupon:'我的优惠券',
}
